apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tkkr1lkrl-nodejs 
  janus-idp.io/tekton: tkkr1lkrl-nodejs
  backstage.io/kubernetes-id: tkkr1lkrl-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tkkr1lkrl-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml