apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tkkr1lkrl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tkkr1lkrl-nodejs 
  name: tkkr1lkrl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tkkr1lkrl-nodejs 
